---
# tasks file for ansible-netplan
- name:       Capturing Existing Configurations
  find:
    paths:    /etc/netplan
    patterns: "*.yml,*.yaml"
  become:     true
  register:   _netplan_configs

- debug:      var=_netplan_configs

- name:       Removing Existing Configurations
  file:
    path:     "{{ item['path'] }}"
    state:    absent
  become:     true
  with_items: "{{ _netplan_configs['files'] }}"
  when:       >
      netplan_remove_existing and
      item['path'] != netplan_config_file and
      netplan_configuration != []

- name:       Configuring Netplan
  template:
    src:      etc/netplan/config.yaml.j2
    dest:     "{{ netplan_config_file }}"
  become:     true
  register:   _netplan_configured
  when:       netplan_configuration != []

- name:       Generating Netplan Configuration
  command:    netplan generate
  become:     true
  register:   _netplan_generated
  when:       _netplan_configured['changed']

- name:       Applying Netplan Configuration
  command:    netplan apply
  become:     true
  when:       _netplan_generated['changed']
