---
- name: Include install tasks
  ansible.builtin.import_tasks: install.yml
  when:
    - netplan_check_install

- name: Include existing config tasks
  ansible.builtin.import_tasks: existing.yml
  when:
    - netplan_remove_existing

- name: Include configure tasks
  ansible.builtin.import_tasks: configure.yml
