---
- name: Generating Netplan Configuration
  ansible.builtin.command: netplan generate
  listen: netplan generate config
  notify: netplan apply config
  become: true
  changed_when: true

- name: Applying Netplan Configuration
  ansible.builtin.command: netplan apply
  listen: netplan apply config
  become: true
  when: netplan_apply
  changed_when: true

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u
  listen: update initramfs
  become: true
  changed_when: true
