---
- name: Converge
  hosts: all
  become: true
  vars:
    debug: true
    netplan_configuration:
      network:
        version: 2
        dummy-devices:
          dm0:
            addresses:
              - 10.42.42.2/32
  tasks:
    - name: "Include ansible-netplan"
      include_role:
        name: "mrlesmithjr.netplan"
